apiVersion: v1
kind: PersistentVolume
metadata:
  name: jumpserver-media-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/server/data/jumpserver-media"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jumpserver-media-claim
  namespace: default
  #annotations:
    #volume.beta.kubernetes.io/storage-class: "nfs-storage"
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
