apiVersion: v1
kind: Service
metadata:
  name: jumpserver
  namespace: default
  labels:
          #app: jumpserver
    app.kubernetes.io/instance: jumpserver
    app.kubernetes.io/name: jumpserver
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 80
    protocol: TCP
  - name: ssh
    port: 2222
    targetPort: 2222
    nodePort: 2222
    protocol: TCP
  selector:
          #app: jumpserver
    app.kubernetes.io/instance: jumpserver
    app.kubernetes.io/name: jumpserver
